#!/usr/bin/env node

var spawn = require('child_process').spawn,
    fs = require('fs'),
    path = require('path'),
    logo = fs.readFileSync(path.join(__dirname,'logo.txt'), 'utf8'),
    service = require('commander'),
    package = require('./package.json');

function start() {

  process.env.AIO_PORT = service.port || 8080;

  var child = spawn('forever-service', ['install', '-s', 'index.js', '--start', 'aioserver'], {
    cwd: __dirname,
    env: process.env,
    detached: true
  });

  console.log(logo);
  console.log('starting service...');

  child.on('error', console.log);

}

function stop() {

  var child = spawn('forever-service', ['delete', 'aioserver'], {
    cwd: __dirname,
    env: process.env,
    detached: true
  });

  console.log('stopping service...');

  child.on('error', console.log);

}

service.version(package.version);
service.option('-p, --port <n>', 'http port', parseInt);
service.command('start').description('installs and starts the service').action(start);
service.command('stop').description('stops and removes the service').action(stop);
service.parse(process.argv);

if (!process.argv.slice(2).length)
  service.outputHelp();

